-- Persistent profile, memory, and conversation-context foundations.
-- Event data is authoritative; profile rows are deterministic projections.

CREATE TABLE user_profile_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_type TEXT NOT NULL,
    source TEXT NOT NULL,
    recipe_id TEXT REFERENCES recipes(id) ON DELETE SET NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    idempotency_key TEXT NOT NULL,
    trace_id TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at TIMESTAMPTZ,
    processing_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_user_profile_events_user_seq UNIQUE (user_id, seq),
    CONSTRAINT uq_user_profile_events_idempotency UNIQUE (user_id, idempotency_key),
    CONSTRAINT ck_user_profile_events_type CHECK (
        event_type IN (
            'quiz_answer', 'constraint_set', 'view', 'favorite', 'make',
            'like', 'dislike', 'feedback', 'skip'
        )
    ),
    CONSTRAINT ck_user_profile_events_source CHECK (
        source IN ('structured_ui', 'chat_confirmed', 'system')
    ),
    CONSTRAINT ck_user_profile_events_recipe_required CHECK (
        recipe_id IS NOT NULL OR
        event_type IN ('quiz_answer', 'constraint_set')
    )
);

CREATE INDEX idx_user_profile_events_user_time
    ON user_profile_events (user_id, seq DESC);

CREATE INDEX idx_user_profile_events_pending
    ON user_profile_events (user_id, seq)
    WHERE processed_at IS NULL;

CREATE TABLE user_profiles (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    schema_version INTEGER NOT NULL DEFAULT 1 CHECK (schema_version > 0),
    constraints JSONB NOT NULL DEFAULT '{}'::jsonb,
    preferences JSONB NOT NULL DEFAULT '{}'::jsonb,
    confidence JSONB NOT NULL DEFAULT '{}'::jsonb,
    profile_revision BIGINT NOT NULL DEFAULT 0 CHECK (profile_revision >= 0),
    last_event_seq BIGINT,
    computed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_memory_statements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    content TEXT NOT NULL CHECK (content <> '' AND char_length(content) <= 1000),
    normalized_key TEXT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    source TEXT NOT NULL,
    retention_policy TEXT NOT NULL DEFAULT 'explicit',
    source_event_id UUID REFERENCES user_profile_events(id) ON DELETE SET NULL,
    source_message_id UUID REFERENCES chat_messages(id) ON DELETE SET NULL,
    confidence NUMERIC(3,2) NOT NULL DEFAULT 0.80
        CHECK (confidence >= 0 AND confidence <= 1),
    status TEXT NOT NULL DEFAULT 'active',
    supersedes_id UUID REFERENCES user_memory_statements(id) ON DELETE SET NULL,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_user_memory_kind CHECK (
        kind IN ('preference', 'constraint', 'context', 'goal')
    ),
    CONSTRAINT ck_user_memory_source CHECK (
        source IN ('structured_ui', 'chat_confirmed', 'chat_auto', 'summary_confirmed')
    ),
    CONSTRAINT ck_user_memory_retention CHECK (
        retention_policy IN ('explicit', 'auto_low_risk', 'temporary_context')
    ),
    CONSTRAINT ck_user_memory_auto_requires_expiry CHECK (
        retention_policy NOT IN ('auto_low_risk', 'temporary_context') OR
        expires_at IS NOT NULL
    ),
    CONSTRAINT ck_user_memory_status CHECK (
        status IN ('active', 'superseded', 'revoked', 'expired')
    )
);

CREATE UNIQUE INDEX uq_user_memory_active_normalized
    ON user_memory_statements (user_id, normalized_key)
    WHERE status = 'active';

CREATE INDEX idx_user_memory_user_active
    ON user_memory_statements (user_id, updated_at DESC)
    WHERE status = 'active';

CREATE TABLE user_memory_settings (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    allow_auto_low_risk BOOLEAN NOT NULL DEFAULT false,
    low_risk_ttl_days INTEGER NOT NULL DEFAULT 180
        CHECK (low_risk_ttl_days BETWEEN 7 AND 365),
    allow_temporary_context BOOLEAN NOT NULL DEFAULT false,
    temporary_context_ttl_days INTEGER NOT NULL DEFAULT 7
        CHECK (temporary_context_ttl_days BETWEEN 1 AND 30),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- A stable user-scoped ordering makes context windows and summary cursors
-- independent of wall-clock ties.
ALTER TABLE chat_messages ADD COLUMN seq BIGINT;

WITH ordered AS (
    SELECT id,
           ROW_NUMBER() OVER (
               PARTITION BY user_id
               ORDER BY created_at, id
           ) AS new_seq
    FROM chat_messages
)
UPDATE chat_messages m
SET seq = o.new_seq
FROM ordered o
WHERE m.id = o.id;

CREATE UNIQUE INDEX uq_chat_messages_user_seq
    ON chat_messages (user_id, seq);

ALTER TABLE chat_messages
    ALTER COLUMN seq SET NOT NULL;

ALTER TABLE chat_messages
    ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('chat_messages', 'seq'),
    COALESCE(MAX(seq), 0) + 1,
    false
) FROM chat_messages;

CREATE INDEX idx_chat_messages_user_seq
    ON chat_messages (user_id, seq DESC);

CREATE TABLE chat_context_summaries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    from_message_id UUID REFERENCES chat_messages(id) ON DELETE CASCADE,
    to_message_id UUID REFERENCES chat_messages(id) ON DELETE CASCADE,
    from_seq BIGINT,
    to_seq BIGINT,
    summary TEXT NOT NULL CHECK (summary <> '' AND char_length(summary) <= 8000),
    covered_message_count INTEGER NOT NULL CHECK (covered_message_count > 0),
    token_estimate INTEGER NOT NULL CHECK (token_estimate >= 0),
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'model',
    trace_id TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_chat_context_summary_range CHECK (
        from_seq IS NULL OR to_seq IS NULL OR from_seq <= to_seq
    ),
    CONSTRAINT ck_chat_context_summary_status CHECK (
        status IN ('active', 'archived', 'invalid')
    )
);

CREATE INDEX idx_chat_context_summaries_user_active
    ON chat_context_summaries (user_id, created_at DESC)
    WHERE status = 'active';

CREATE TABLE chat_context_state (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    last_summarized_message_id UUID REFERENCES chat_messages(id) ON DELETE SET NULL,
    active_summary_id UUID REFERENCES chat_context_summaries(id) ON DELETE SET NULL,
    recent_window INTEGER NOT NULL DEFAULT 16 CHECK (recent_window BETWEEN 4 AND 40),
    target_summary_tokens INTEGER NOT NULL DEFAULT 700
        CHECK (target_summary_tokens BETWEEN 100 AND 2000),
    context_token_budget INTEGER NOT NULL DEFAULT 7000
        CHECK (context_token_budget BETWEEN 1000 AND 32000),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO user_memory_settings (user_id)
SELECT id FROM users
ON CONFLICT (user_id) DO NOTHING;
